version: '3.7'

services:
  running-api:
    container_name: running-api
    image: running-api:stage
    build:
      context: .
      target: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080
    command: npm run start:prod
    environment:
      NODE_ENV: production
      SERVER_PORT: 8080
      DB_HOST: ${DB_HOST}
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_PORT: ${DB_PORT}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_JWKS_URI: ${GOOGLE_JWKS_URI}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
    networks:
      - dockernet

networks:
  dockernet:
    external: true
