name: Deployment

on:
  push:
    branches: [ stage ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - run: docker build --file Dockerfile --tag running-api:stage .
      - run: docker save running-api:stage | gzip > runningapi_latest.tar.gz
      - run: mkdir image && mv runningapi_latest.tar.gz image
      - name: Deploy
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.CERTIFICATE }}
          REMOTE_HOST: ${{ secrets.HOSTNAME }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          SOURCE: image/
          TARGET: /home/${{ secrets.USERNAME }}/
          SCRIPT_AFTER: |
            chmod +x start-app.sh
            ./start-app.sh